services:
  app_my_ts:
    build:
      context: .
      dockerfile: .hasura-connector/Dockerfile
    environment:
      HASURA_SERVICE_TOKEN_SECRET: $APP_MY_TS_HASURA_SERVICE_TOKEN_SECRET
      OTEL_EXPORTER_OTLP_ENDPOINT: $APP_MY_TS_OTEL_EXPORTER_OTLP_ENDPOINT
      OTEL_SERVICE_NAME: $APP_MY_TS_OTEL_SERVICE_NAME
    extra_hosts:
      - local.hasura.dev:host-gateway
    ports:
      - 7244:8080
